swagger: '2.0'
info:
  description: EW REST API for SSO - Identity Service - Management of Identities (Users/Contacts)
  version: '1.0'
  termsOfService: 'http://www.karumien.com/terms/'
  Identity:
    email: info@karumien.com
  title: Identity Service
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /api/v1/iam
schemes:
  - http
paths:
  /identities:
    post:
      summary: Create Identity
      description: Create Identity in target SSO
      operationId: createIdentity
      parameters:
        - in: body
          name: identity
          description: The Identity to create
          schema:
            $ref: '#/definitions/IdentityInfo'
            example:
              lastName: Novak
              firstName: Karel
              username: KajaN
              email: KajaN@eurowag.com
      responses:
        '201':
          description: Successfully created
          schema:
            $ref: '#/definitions/IdentityInfo'
            example:
              crmContactId: 6287994b-0245-4ca7-8eb4-777230b2f91f
              crmAccountId: 31034
              lastName: Novak
              firstName: Karel
              username: KajaN
              email: KajaN@eurowag.com
        '409':
          description: Identity already exists (conflict username/crmContactId)
  /identities/{crmContactId}:
    get:
      summary: "Get detail of the given Identity"
      description: "Method returns detail information about Identity."
      operationId: getIdentity
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity unique CRM ID
          required: true
          type: string       
      responses:
        '200':
          description: Successfully returned Identity's info
          schema:
            $ref: '#/definitions/IdentityInfo'
        '410':
          description: Gone
    delete:
      summary: "Remove existing Identity"
      operationId: deleteIdentity
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity Unique ID
          required: true
          type: string       
      responses:
        '200':
          description: Successfully removed existing Identity
        '410':
          description: Identity Gone
  /identities/{crmContactId}/credentials:
    post:
      summary: "Create Identity credentials"
      description: "Method to create Identity credentials for given customer"
      operationId: createIdentityCredentials
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity unique CRM ID
          required: true
          type: string       
        - in: body
          name: credentials
          description: The Credentials for Identity to create/change
          schema:
            $ref: '#/definitions/Credentials'
            example:
              username: "midie"
              password: "#123456."
              temporary: true
      responses:
        '201':
          description: "Identity creadentials has been created or reset"
        '410':
          description: Identity Gone
        '422':
          description: Can't create Identity's credentials
  /identities/nav4/{nav4Id}:
    get:
      summary: "Get detail of the given Identity"
      description: "Method returns detail information about Identity."
      operationId: getIdentityNav4
      parameters:
        - name: nav4Id
          in: path
          description: Filtering by Identity unique NAV4 ID
          required: true
          type: string       
      responses:
        '200':
          description: Successfully returned Identity's info
          schema:
            $ref: '#/definitions/IdentityInfo'
        '410':
          description: Gone
  /identities/nav4/{nav4Id}/credentials:
    post:
      summary: "Create Identity credentials"
      description: "Method to create Identity credentials for given customer"
      operationId: createIdentityNav4Credentials
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity unique NAV4 ID
          required: true
          type: string       
        - in: body
          name: credentials
          description: The Credentials for Identity to create/change
          schema:
            $ref: '#/definitions/Credentials'
            example:
              username: "midie"
              password: "#123456."
              temporary: true
      responses:
        '201':
          description: "Identity creadentials has been created or reset"
        '410':
          description: Identity Gone
        '422':
          description: Can't create Identity's credentials
  /identities/{crmContactId}/credentials/block:
    put:
      summary: "Block Identity"
      operationId: blockIdentity
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity unique CRM ID
          required: true
          type: string       
      responses:
        '200':
          description: "Identity successfully blocked"
        '410':
          description: Identity Gone
    delete:
      summary: "Unblock Identity"
      operationId: unblockIdentity
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity unique CRM ID
          required: true
          type: string       
      responses:
        '200':
          description: "Identity successfully unblocked"
        '410':
          description: Identity Gone
  /identities/{crmContactId}/credentials/reset:
    post:
      summary: "Reset Identity credentials"
      description: "Method to reset Identity credentials"
      operationId: resetIdentityCredentials
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity unique CRM ID
          required: true
          type: string       
      responses:
        '201':
          description: "Successfully sent email for password reset"
        '410':
          description: Identity Gone
        '422':
          description: Can't reset Identity's credentials
  /identities/{crmContactId}/pin:
    post:
      summary: "Create/Reset Driver PIN"
      description: "Method to create/reset driver's PIN for given driver"
      operationId: "createDriverPin"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Driver Unique ID
          required: true
          type: string       
        - in: body
          name: pin
          description: PIN for Driver to create/change
          schema:
            $ref: '#/definitions/DriverPin'
            example:
              pin: "1234"
      responses:
        '201':
          description: "Driver PIN has been created/update"
        '410':
          description: Driver Gone  
        '422':
          description: Can't create/update Driver's PIN 
    get:
      summary: "Get Driver PIN"
      operationId: "getDriverPin"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Driver Unique ID
          required: true
          type: string       
      responses:
        '200':
          description: "Driver PIN has been created/update"
          schema:
            $ref: '#/definitions/DriverPin'
            example:
              pin: "1234"
        '410':
          description: Driver or pin Gone  
    delete:
      summary: "Delete Driver PIN"
      operationId: "deleteDriverPin"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Driver Unique ID
          required: true
          type: string       
      responses:
        '200':
          description: "Driver PIN has been deleted"
        '410':
          description: Driver Gone 
  /identities/{crmContactId}/impersonate:
    post:
      summary: "Impersonate Identity"
      description: "Method for impersonation of specified Identity"
      operationId: "impersonateIdentity"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity unique CRM ID
          required: true
          type: string       
      responses:
        '200':
          description: "Identity has been impersonated"
        '410':
          description: Identity Gone
  /identities/{crmContactId}/logout:
    post:
      summary: "Logout Identity's session"
      description: "Method for logout session of specified Identity"
      operationId: "logoutIdentity"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity unique CRM ID
          required: true
          type: string       
      responses:
        '200':
          description: "Identity has been logged out of all sessions"
        '410':
          description: Identity Gone
  /identities/{crmContactId}/roles/binary:
    get:
      summary: "Get assigned Roles on Identity in Binary Representation"
      operationId: "getIdentityRolesBinary"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity CRM ID
          required: true
          type: string   
      produces:
        - text/plain
      responses:
        '200':
          description: Identity's assigned Roles in Binary Representation 
        '410':
          description: Identity Gone  
  /identities/{crmContactId}/roles:
    get:
      summary: "Get assigned Roles on Identity"
      operationId: "getIdentityRoles"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity CRM ID
          required: true
          type: string   
      responses:
        '200':
          description: Identity's assigned roles
          schema:
            type: array
            items:
              $ref: '#/definitions/RoleInfo'
        '410':
          description: Identity Gone
    put:
      summary: "Assign roles on Identity"
      operationId: "assignIdentityRoles"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity CRM ID
          required: true
          type: string       
        - in: body
          name: roles
          description: List of Identity's ID to assign
          schema:
            type: array
            items:
              type: string                    
      responses:
        '202':
          description: Successfully assigned Roles to Identity
        '410':
          description: Identity Gone
    delete:
      summary: "Unassign Roles on Identity"
      operationId: "unassignIdentityRoles"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity CRM ID
          required: true
          type: string       
        - in: body
          name: roles
          description: List of Identity's ID to unassign
          schema:
            type: array
            items:
              type: string                    
      responses:
        '202':
          description: Successfully unsassigned Roles from Identity
        '410':
          description: Identity Gone
  /identities/{crmContactId}/roles/{roleId}:
    get:
      summary: "Get assigned Roles on Identity"
      operationId: "getIdentityRole"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity CRM ID
          required: true
          type: string   
        - name: roleId
          in: path
          description: Filtering by Identity ID
          required: true
          type: string   
      responses:
        '200':
          description: Role is assigned to Identity
        '410':
          description: Identity Gone
        '422':
          description: Role not assigned
    put:
      summary: "Assign Role to Identity"
      operationId: "assignIdentityRole"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity CRM ID
          required: true
          type: string       
        - name: roleId
          in: path
          description: Filtering by Identity ID
          required: true
          type: string    
      responses:
        '202':
          description: Successfully assigned Role on Identity
        '410':
          description: Identity Gone
        '422':
          description: Role for Identity not assigned
    delete:
      summary: "Remove Role on Identity"
      operationId: "unassignIdentityRole"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity CRM ID
          required: true
          type: string       
        - name: roleId
          in: path
          description: Filtering by Identity ID
          required: true
          type: string    
      responses:
        '202':
          description: Successfully unassigned Role from Identity
        '410':
          description: Identity Gone
        '422':
          description: Role not unassigned
  /identities/exists:
    get:
      summary: "Check if exist Identity by specified attributes"
      operationId: exists
      parameters:
        - in: query
          name: username
          description: Identity existency check by username
          required: false
          type: string 
        - in: query
          name: crmContactId
          description: Identity existency check by CRM Contact ID
          required: false
          type: string 
        - in: query
          name: nav4Id
          description: Identity existency check by NAV4 ID 
          required: false
          type: string 
      responses:
        '200':
          description: Found Identity specified by filter
        '410':
          description: Identity specified by filter not found
definitions:
  IdentityInfo:
    type: object
    description: "Basic information about Identity"
    required:
      - crmAccountId
      - crmContactId
    properties:
      identityId:
        type: string
        description: Identity's ID 
      crmAccountId:
        type: string
        description: Identity's CRM Account ID
      crmContactId:
        type: string
        description: Identity's Unique ID 
      nav4Id:
        type: string
        description: Identity's Unique NAV4 ID 
      lastName:
        type: string
        description: "Last name/ surname of the Identity"
        maxLength: 50
      firstName:
        type: string
        description: "First name of the Identity"
        maxLength: 50
      username:
        type: string
        description: "Unique username"
        maxLength: 50
      email:
        type: string
        description: "Primary email used primary for password reset"
        maxLength: 100
      emailVerified:
        type: boolean
        description: "Verified status of itentity email"
      phone:
        type: string
        description: "Phone used primary for OTP"
        maxLength: 30
      globalEmail:
        type: string
        description: "Contact email - can be company global"
        maxLength: 100
      locale:
        type: string
        description: "User's default Locale"
        maxLength: 50  
    example:
      crmAccountId: 31034
      crmContactId: fe29248c-f3aa-4310-8fcf-91eacdd324xx
      lastName: Novak
      firstName: Karel
      email: KajaN@eurowag.com
      emailVerified: true
  Credentials:
    type: object
    description: "Object for setting of Identity credential"
    required:
      - username
    properties:
      username:
        type: string
        description: "Unique username"
        maxLength: 50
      password:
        type: string
        maxLength: 50
      currentPassword:
        type: string
        maxLength: 50
      temporary:
        type: boolean
        description: "Temporary - need reset after first login"
    example:
      - username: "midie"
        password: "#123456."
      - password: "#123456."
        temporary: true      
      - password: "#123456."
        currentPassword: "oldPassword"
        temporary: true      
  DriverPin:
    type: object
    description: "Driver's PIN Definition"
    required:
      - pin
    properties:
      pin:
        type: string
        example: "123456"
        maxLength: 10
  RoleInfo:
    type: object
    description: "Basic information about Role"
    required:
      - roleId
    properties:
      roleId:
        type: string
        description: "Unique Role ID (Role Name)"
        maxLength: 50
      description:
        type: string
        description: "Role description"
        maxLength: 255
      clientId:
        type: string
        maxLength: 250
        description: Client Id (for client roles)
      clientRole:
        type: boolean
        description: "Identify Client Role (not realm role)"
    example:
      id: fd65248c-f3aa-4310-8fcf-91eacdd324xx
      name: First Role
      description: Role description
      clientId: 9abedf80-7413-4751-9b73-84d07a32e11c
      clientRole: true