swagger: '2.0'
info:
  description: EW REST API for SSO - Account Service - Management of Accounts (Customers)
  version: '1.0'
  termsOfService: 'http://www.karumien.com/terms/'
  contact:
    email: info@karumien.com
  title: Account Service
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /api/v1/iam
schemes:
  - http
paths:
  /accounts:
    get:
      summary: "Get known Accounts"
      operationId: "getAccounts"
      responses:
        '200':
          description: Successfully found Accounts
          schema:
            type: array
            items:
              $ref: '#/definitions/AccountInfo'
    post:
      summary: Create Account 
      description: Create Account in target SSO
      operationId: createAccount
      parameters:
        - in: body
          name: Account
          description: The Account to create
          schema:
            $ref: '#/definitions/AccountInfo'
      responses:
        '201':
          description: Successfully created
          schema:
            $ref: '#/definitions/AccountInfo'
        '409':
          description: Account already exists (conflict crmAccountId)
  /accounts/{crmAccountId}:
    get:
      summary: "Get detail of the given Account"
      description: "Method returns detail information about Account."
      operationId: "getAccount"
      parameters:
        - in: path
          name: crmAccountId
          description: Filtering by Account CRM ID
          required: true
          type: string       
      responses:
        '200':
          description: Successfully returned Account's info
          schema:
            $ref: '#/definitions/AccountInfo'
        '410':
          description: Gone
    delete:
      summary: "Remove existing Account"
      operationId: "deleteAccount"
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account CRM ID
          required: true
          type: string       
      responses:
        '200':
          description: Successfully removed existing Account
        '410':
          description: Account Gone
  /accounts/{crmAccountId}/modules:
    get:
      summary: "Get Active Modules on Account"
      operationId: "getAccountModules"
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account CRM ID
          required: true
          type: string   
      responses:
        '200':
          description: Account's activated modules
          schema:
            type: array
            items:
              $ref: '#/definitions/ModuleInfo'
        '410':
          description: Account Gone
    put:
      summary: "Activate Modules on Account"
      operationId: "activateAccountModules"
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account CRM ID
          required: true
          type: string       
        - in: body
          name: modules
          description: List of Module's ID to activate
          schema:
            type: array
            items:
              type: string                    
      responses:
        '202':
          description: Successfully Activated Modules on Account
        '410':
          description: Account Gone
    delete:
      summary: "Deactivate Modules on Account"
      operationId: "deactivateAccountModules"
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account CRM ID
          required: true
          type: string       
        - in: body
          name: modules
          description: List of Module's ID to activate
          schema:
            type: array
            items:
              type: string                    
      responses:
        '202':
          description: Successfully deactivated Modules on Account
        '410':
          description: Account Gone
  /accounts/{crmAccountId}/modules/{moduleId}:
    get:
      summary: "Get Active Module on Account"
      operationId: "getAccountModule"
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account CRM ID
          required: true
          type: string   
        - name: moduleId
          in: path
          description: Filtering by Module ID
          required: true
          type: string   
      responses:
        '200':
          description: Module is active on Account
        '410':
          description: Account Gone
        '422':
          description: Module Unprocessable entity
    put:
      summary: "Activate Module on Account"
      operationId: "activateAccountModule"
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account CRM ID
          required: true
          type: string       
        - name: moduleId
          in: path
          description: Filtering by Module ID
          required: true
          type: string    
      responses:
        '202':
          description: Successfully activated Module on Account
        '410':
          description: Account Gone
        '422':
          description: Module Unprocessable entity
    delete:
      summary: "Deactivate Module on Account"
      operationId: "deactivateAccountModule"
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account CRM ID
          required: true
          type: string       
        - name: moduleId
          in: path
          description: Filtering by Module ID
          required: true
          type: string    
      responses:
        '202':
          description: Successfully deactivated Module on Account
        '410':
          description: Account Gone
        '422':
          description: Module not deactivated
  /accounts/{crmAccountId}/roles:
    get:
      summary: "Get Active Roles on Account"
      operationId: "getAccountRoles"
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account CRM ID
          required: true
          type: string   
      responses:
        '200':
          description: Account's activated roles
          schema:
            type: array
            items:
              $ref: '#/definitions/RoleInfo'
        '410':
          description: Roles Gone
  /accounts/{crmAccountId}/identities:
    post:
      summary: Create Identity
      description: Create Identity in target SSO
      operationId: createAccountIdentity
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account CRM ID
          required: true
          type: string       
        - in: body
          name: identity
          description: The Identity to create
          schema:
            $ref: '#/definitions/IdentityInfo'
      responses:
        '201':
          description: Successfully created
          schema:
            $ref: '#/definitions/IdentityInfo'            
        '409':
          description: Identity already exists (conflict username/crmContactId)
    get:
      summary: Return all Identities registered for Account
      operationId: getAccountIdentities
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account CRM ID
          required: true
          type: string
        - in: body
          name: crmContactIds
          required: false
          description: CRM Contacts IDs
          schema:
            type: array
            items: 
              type: string
      responses:
        '200':
          description: Successfully returned Identities
          schema:
            type: array            
            items:
              $ref: '#/definitions/IdentityInfo'
        '410':
          description: Account Gone
  /accounts/{crmAccountId}/identities/{crmContactId}:
    get:
      summary: "Get detail of the given Identity"
      description: "Method returns detail information about Identity."
      operationId: getAccountIdentity
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account unique CRM ID
          required: true
          type: string
        - name: crmContactId
          in: path
          description: Filtering by Identity unique CRM ID
          required: true
          type: string    
      responses:
        '200':
          description: Successfully returned Identity's info
          schema:
            $ref: '#/definitions/IdentityInfo'
        '410':
          description: Gone
    delete:
      summary: "Remove existing Identity"
      operationId: deleteAccountIdentity
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account unique CRM ID
          required: true
          type: string
        - name: crmContactId
          in: path
          description: Filtering by Identity unique CRM ID
          required: true
          type: string    
      responses:
        '200':
          description: Successfully removed existing Identity
        '410':
          description: Identity Gone
  /accounts/{crmAccountId}/identities/roles:
    get:
      summary: "Get detail of the given Identity"
      operationId: getAccountIdentitiesRoles
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account unique CRM ID
          required: true
          type: string
        - in: body
          name: crmContactIds
          required: false
          description: CRM Contacts IDs
          schema:
            type: array
            items: 
              type: string
      responses:
        '200':
          description: Successfully returned Identity's Roles
          schema:
            type: array
            items:
              $ref: '#/definitions/IdentityRoleInfo'
        '410':
          description: Gone  
  /accounts/{crmAccountId}/identities/{crmContactId}/rights:
    get:
      summary: "Get Identity's Rights Ids"
      operationId: getAccountIdentityRightIds
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account unique CRM ID
          required: true
          type: string
        - name: crmContactId
          in: path
          description: Filtering by Identity unique CRM ID
          required: true
          type: string       
      responses:
        '200':
          description: Successfully returned Identity's Roles
          schema:
            type: array
            items:
              type: string
        '410':
          description: Gone
  /accounts/{crmAccountId}/identities/{crmContactId}/roles:
    get:
      summary: "Get Identity's Roles Ids"
      operationId: getAccountIdentityRoleIds
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account unique CRM ID
          required: true
          type: string
        - name: crmContactId
          in: path
          description: Filtering by Identity unique CRM ID
          required: true
          type: string       
      responses:
        '200':
          description: Successfully returned Identity's Roles
          schema:
            type: array
            items:
              type: string
        '410':
          description: Gone
    put:
      summary: "Assign roles on Identity"
      operationId: assignAccountIdentityRoles
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account unique CRM ID
          required: true
          type: string
        - name: crmContactId
          in: path
          description: Filtering by Identity unique CRM ID
          required: true
          type: string   
        - in: body
          name: roles
          description: List of Roles's ID to deactivate
          schema:
            type: array
            items:
              type: string  
      responses:
        '202':
          description: Successfully added roles to Identity
        '410':
          description: Identity Gone
    delete:
      summary: "Unassign roles on Identity"
      operationId: unassignAccountIdentityRoles
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account unique CRM ID
          required: true
          type: string
        - name: crmContactId
          in: path
          description: Filtering by Identity unique CRM ID
          required: true
          type: string   
        - in: body
          name: roles
          description: List of Roles's ID to deactivate
          schema:
            type: array
            items:
              type: string  
      responses:
        '202':
          description: Successfully removed roles of Identity
        '410':
          description: Identity Gone
  /accounts/{crmAccountId}/identities/{crmContactId}/roles/{roleId}:
    get:
      summary: "Get assigned Roles on Identity"
      operationId: "getAccountIdentityRole"
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account unique CRM ID
          required: true
          type: string
        - name: crmContactId
          in: path
          description: Filtering by Identity CRM ID
          required: true
          type: string   
        - name: roleId
          in: path
          description: Filtering by Role ID
          required: true
          type: string   
      responses:
        '200':
          description: Role is assigned to Identity
        '410':
          description: Identity Gone
        '422':
          description: Role not assigned
    put:
      summary: "Assign Role to Identity"
      operationId: "assignAccountIdentityRole"
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account unique CRM ID
          required: true
          type: string
        - name: crmContactId
          in: path
          description: Filtering by Identity CRM ID
          required: true
          type: string       
        - name: roleId
          in: path
          description: Filtering by Role ID
          required: true
          type: string    
      responses:
        '202':
          description: Successfully assigned Role on Identity
        '410':
          description: Identity Gone
        '422':
          description: Role for Identity not assigned
    delete:
      summary: "Remove Role on Identity"
      operationId: "unassignAccountIdentityRole"
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account unique CRM ID
          required: true
          type: string
        - name: crmContactId
          in: path
          description: Filtering by Identity CRM ID
          required: true
          type: string       
        - name: roleId
          in: path
          description: Filtering by Identity ID
          required: true
          type: string    
      responses:
        '202':
          description: Successfully unassigned Role from Identity
        '410':
          description: Identity Gone
        '422':
          description: Role not unassigned
  /account/{crmAccountId}/hierarchy:
    get:
      summary: Hierarchy definition for Account - modules and right groups (translated, filtered by activated services)
      operationId: getAccountHierarchy
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account CRM ID
          required: true
          type: string
      responses:
        '200':
          description: Successfully returned Identities
          schema:
            type: array            
            items:
              $ref: '#/definitions/ModuleInfo'
        '410':
          description: Account Gone  
  /accounts/{crmAccountId}/identities/{crmContactId}/credentials:
    post:
      summary: "Add Account Identity credentials"
      description: "Method to create Identity credentials for given customer"
      operationId: createIdentityCredentials
      parameters:
        - name: crmAccountId
          in: path
          description: Filtering by Account unique CRM ID
          required: true
          type: string
        - name: crmContactId
          in: path
          description: Filtering by Identity unique CRM ID
          required: true
          type: string       
        - in: body
          name: credentials
          description: The Credentials for Identity to create/change
          schema:
            $ref: '#/definitions/Credentials'
            example:
              username: "midie"
              password: "#123456."
              temporary: true
      responses:
        '201':
          description: "Identity creadentials has been created or reset"
        '410':
          description: Identity Gone
        '422':
          description: Can't create Identity's credentials
definitions:
  IdentityInfo:
    type: object
    description: "Basic information about Identity"
    required:
      - crmAccountId
      - crmContactId
    properties:
      identityId:
        type: string
        description: Identity's ID 
      crmAccountId:
        type: string
        description: Identity's CRM Account ID
      crmContactId:
        type: string
        description: Identity's Unique ID 
      nav4Id:
        type: string
        description: Identity's Unique NAV4 ID 
      lastName:
        type: string
        description: "Last name/ surname of the Identity"
        maxLength: 50
      firstName:
        type: string
        description: "First name of the Identity"
        maxLength: 50
      username:
        type: string
        description: "Unique username"
        maxLength: 50
      email:
        type: string
        description: "Primary email used primary for password reset"
        maxLength: 100
      emailVerified:
        type: boolean
        description: "Verified status of itentity email"
      phone:
        type: string
        description: "Phone used primary for OTP"
        maxLength: 30
      globalEmail:
        type: string
        description: "Contact email - can be company global"
        maxLength: 100
      locale:
        type: string
        description: "User's default Locale"
        maxLength: 50  
    example:
      crmAccountId: 31034
      crmContactId: fe29248c-f3aa-4310-8fcf-91eacdd324xx
      lastName: Novak
      firstName: Karel
      email: KajaN@eurowag.com
      emailVerified: true
  IdentityRoleInfo:
    type: object
    description: "Basic information Identity Roles"
    required:
      - crmAccountId
      - crmContactId
    properties:
      crmAccountId:
        type: string
        description: Identity's CRM Account ID
      crmContactId:
        type: string
        description: Identity's Unique ID 
      nav4Id:
        type: string
        description: Identity's Unique NAV4 ID 
      roles:
        type: array
        items:
          type: string
  AccountInfo:
    type: object
    description: "Basic information about Account"
    required:
      - crmAccountId
      - name
    properties:
      crmAccountId:
        type: string
        description: Account CRM ID 
      name:
        type: string
        description: "Account Name"
        maxLength: 100
      compRegNo:
        type: string
        maxLength: 20
        description: Account Registration Number
      contactEmail:
        type: string
        description: "Contact Email"
        maxLength: 200
    example:
      id: 31034
      name: Some AUTODOPRAVA, s.r.o.
      compRegNo: 6484605
      contactEmail: info@doprava.cz
  ModuleInfo:
    type: object
    description: "Basic information about Module"
    required:
      - moduleId
    properties:
      moduleId:
        type: string
        example: "MODULE_TLM01"
        maxLength: 40
      description:
        type: string
        example: "Map"
        maxLength: 300
      businessPriority:
        type: integer
        description: Order by priority (1 is highest priority/first)        
      groups:
        type: array
        items:
          $ref: "#/definitions/RightGroup"
  RightGroup:
    type: object
    description: Rigth's logical group
    properties:
      code:
        type: string
        description: unique prefix ie. TLM_MOD
      description:
        type: string
        description: Translated name of group
      businessPriority:
        type: integer
        description: Order by priority (1 is highest priority/first)        
  RoleInfo:
    type: object
    description: "Basic information about Role"
    required:
      - roleId
    properties:
      roleId:
        type: string
        description: "Unique Role ID (Role Name)"
        maxLength: 50
      description:
        type: string
        description: "Role description"
        maxLength: 255
      crmAccountId:
        type: string
        description: Custom role for account
      roles:
        type: array
        items:
          type: string
      rights:
        type: array
        items:
          type: string
  Credentials:
    type: object
    description: "Object for setting of Identity credential"
    required:
      - username
    properties:
      username:
        type: string
        description: "Unique username"
        maxLength: 50
      password:
        type: string
        maxLength: 50
      currentPassword:
        type: string
        maxLength: 50
      temporary:
        type: boolean
        description: "Temporary - need reset after first login"
    example:
      - username: "midie"
        password: "#123456."
      - password: "#123456."
        temporary: true      
      - password: "#123456."
        currentPassword: "oldPassword"
        temporary: true
  ErrorMessageCode:
    type: string
    description: Master Error Code
    enum:
      - CLIENT_ERROR
  ErrorCode:
    type: string
    description: Error codes for attributes
    enum:
      - invalid-username
      - invalid-password  
  ErrorData:
    type: object
    description: EW ErrorMessage model data
    required:
    - code
    properties:
      code:
        $ref: "#/definitions/ErrorCode"
        description: ie. invalid-phone-number-format
      attribute: 
        type: string
        description: ie. phoneNumberPrimary
      description:
        type: string
        description: ie. Invalid phone number format. Valid is XXX XXX XXX
      data:
        type: object
  ErrorMessage:
    type: object
    description: EW ErrorMessage model
    required:
    - errno
    - errcode
    properties:
      errno: 
        type: integer
        default: -1
      errcode: 
        $ref: "#/definitions/ErrorMessageCode"
        type: string
        maxLength: 50
      errmsg: 
        type: string
        maxLength: 250
        description: Optional error message
      errdata:
        type: array
        items:
          $ref: "#/definitions/ErrorData"